kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-go-controller
  labels:
    app.kubernetes.io/name: ingress-go-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-go-controller
subjects:
  - kind: ServiceAccount
    name: ingress-go-controller
    namespace: ingress-go

